/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://z3fo7hb6xjbz7k3lrkdvr33wy4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tajuqtmwnzao7neitdhohvzs6q",
    "aws_cognito_identity_pool_id": "us-east-2:3c11197d-8e29-4601-bd05-7aad9adc7077",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6tdBRRpa0",
    "aws_user_pools_web_client_id": "ovtusbkjjp81lk0sg5r6unse4",
    "oauth": {},
    "aws_user_files_s3_bucket": "farmdigitals3bucket113105-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
